In [1]:
import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'
import numpy as np
import simpy
import matplotlib.pyplot as plt
import random
import pandas as pd

In [2]:
class Patient:
    def __init__(self, id):
        self.id = id
        self.arrival_time = None
        self.service_start_time = None
        self.service_end_time = None
        self.room = None
        self.real_service_time = None

In [3]:
class Room:
    def __init__(self, id, env):
        self.id = id
        self.patients_served = 0
        self.no_show = 0
        self.queue = []
        self.queue_len_dict = dict()
        self.resource = simpy.Resource(env, capacity=1)
    def update_queue_len_dict(self, curr_time):
        self.queue_len_dict[curr_time] = len(self.queue)

In [16]:
class Clinic:
    def __init__(self, number_of_rooms, planned_service_time, no_show=0.2, seed=None, sim_time=480):
        self.curr_patient_id = 1
        self.env = simpy.Environment()
        self.planned_service_time = planned_service_time
        self.no_show = no_show
        self.seed = seed
        self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(number_of_rooms)]
        self.processed_patients = []
        self.sim_time = sim_time

        if self.seed:
            random.seed(self.seed)
            np.random.seed(self.seed)

    def readable_time(self):
        hours = 8 + int(self.env.now // 60)
        minutes = int(self.env.now % 60)
        if len(str(minutes)) == 1:
            return f"{hours}:0{minutes}"
        return f"{hours}:{minutes}"

    def generate_patients(self, room):

        def randomized_service_time(mean=15, std=2):
            return max(np.random.normal(mean, std), 1)

        def time_between_new_patients():
            return self.planned_service_time

        while True:
            if self.env.now > self.sim_time - self.planned_service_time:  # Pacjenci nie przychodzą przed {service_time} zamknięciem
                break

            patient = Patient(id=f"{room.id}.{self.curr_patient_id}")
            patient.room = room.id
            patient.real_service_time = randomized_service_time()

            if random.random() < self.no_show:  #pacjent nie przyszedl
                print(f'Czas {self.readable_time()}: Pacjent {patient.id} nie pojawił w gabinecie {room.id} w ciągu {self.planned_service_time} minut')
                room.no_show += 1

            else:  #pacjent przyszedl
                patient.arrival_time = self.env.now
                print(f"Czas {self.readable_time()}: Pacjent {patient.id} przybył do kliniki")
                self.env.process(self.serve_patient(patient, room))

            self.curr_patient_id += 1
            yield self.env.timeout(time_between_new_patients())

    def serve_patient(self, patient, room):
        room.queue.append(patient.id)
        room.update_queue_len_dict(curr_time=self.env.now)

        with room.resource.request() as request:
            yield request
            patient.service_start_time = self.env.now
            room.queue.remove(patient.id)
            room.update_queue_len_dict(curr_time=self.env.now)

            print(f"Czas {self.readable_time()}: Pacjent {patient.id} wchodzi do gabinetu {room.id} ")

            yield self.env.timeout(patient.real_service_time)

            patient.service_end_time = self.env.now
            room.patients_served += 1
            print(f"Czas {self.readable_time()}: Pacjent {patient.id} wychodzi z gabinetu {room.id}")
            self.processed_patients.append(patient)

    # def reset(self):
    #     self.env = simpy.Environment()
    #     self.curr_patient_id = 1
    #     self.list_rooms = [Gabinet(id=i + 1) for i in range(len(self.list_rooms))]
    #     self.rooms = simpy.Store(self.env, capacity=len(self.list_rooms))
    #     for room in self.list_rooms:
    #         self.rooms.put(room)
    #     self.processed_patients = []
    #     # ----
    #     self.env = simpy.Environment()
    #     self.curr_patient_id = 1
    #     self.planned_service_time = planned_service_time
    #     self.no_show = no_show
    #     self.seed = seed
    #     self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(number_of_rooms)]
    #     self.processed_patients = []
    #     self.sim_time = sim_time

    def run(self, day=1):
        def sum_queue_len_data():
            all_times = set()
            for room in self.list_rooms:
                all_times.update(room.queue_len_dict.keys())

            all_times = sorted(all_times)
            queue_data = []
            last_known = {room.id: 0 for room in self.list_rooms}  # cache

            for time in all_times:
                for room in self.list_rooms:
                    if time in room.queue_len_dict:
                        last_known[room.id] = room.queue_len_dict[time]

                total_queue = sum(last_known.values())
                queue_data.append({
                    'day': day,
                    'time': time,
                    'total_queue_length': total_queue
                })
            queue_data = pd.DataFrame(queue_data)
            queue_data = queue_data.set_index(["day", "time"])
            return queue_data
        
        for room in self.list_rooms:
            self.env.process(self.generate_patients(room))
        self.env.run(until=self.sim_time + 0.01)
        df = pd.DataFrame([
            {
                "day": day,
                "id": p.id,
                "room": p.room,
                "arrival_time": p.arrival_time,
                "service_start_time": p.service_start_time,
                "service_end_time": p.service_end_time,
                "service_time": p.service_end_time - p.service_start_time,
                "waiting_time": p.service_start_time - p.arrival_time
            }
            for p in self.processed_patients
        ])
        df = df.set_index("id")
        queue_df = sum_queue_len_data()
        return df, queue_df

    def run_multiple_times(self, n):

        # sum_no_show = 0
        # sum_patients_served = 0

        for i in range(1, n + 1):
            print(f"-----------{i}-----------")
            self.env = simpy.Environment()
            self.curr_patient_id = 1
            self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(len(self.list_rooms))]
            self.processed_patients = []
            single_df, single_queue_df = self.run(i)

            # for room in self.list_rooms:
            #     sum_no_show += room.no_show
            #     sum_patients_served += room.patients_served

            multiple_df = pd.concat([multiple_df, single_df], ignore_index=True) if i > 1 else single_df
            multiple_queue_df = pd.concat([multiple_queue_df, single_queue_df]) if i > 1 else single_queue_df
        # return multiple_df, sum_patients_served, sum_no_show
        return multiple_df, multiple_queue_df

In [5]:
clinic1 = Clinic(number_of_rooms=3, planned_service_time=15, sim_time=120)

In [6]:
df, q_df = clinic1.run()

Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:00: Pacjent 3.3 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:13: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:29: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:44: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:46: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:46: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:58: Pacjent 2.11 wychodzi z gabinetu 2
Czas 8:59: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:02: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:02: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:15: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:15: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:27: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:31: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:47: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:47: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:59: Pacjent 1.22 wychodzi z gabinetu 1

In [7]:
display(df)

,day,room,arrival_time,service_start_time,service_end_time,service_time,waiting_time
id,,,,,,,
1.1,1,1,0,0.000000,13.814933,13.814933,0.000000
1.4,1,1,15,15.000000,27.464361,12.464361,0.000000
2.5,1,2,15,15.000000,29.926871,14.926871,0.000000
3.6,1,3,15,15.000000,30.878880,15.878880,0.000000
1.7,1,1,30,30.000000,44.699753,14.699753,0.000000
3.9,1,3,30,30.878880,46.506976,15.628096,0.878880
2.11,1,2,45,45.000000,58.783939,13.783939,0.000000
1.10,1,1,45,45.000000,59.706860,14.706860,0.000000
3.12,1,3,45,46.506976,62.145497,15.638521,1.506976
3.15,1,3,60,62.145497,75.005773,12.860276,2.145497
1.13,1,1,60,60.000000,75.640157,15.640157,0.000000
3.18,1,3,75,75.005773,87.904755,12.898982,0.005773
1.16,1,1,75,75.640157,91.041564,15.401407,0.640157
2.17,1,2,75,75.000000,91.051556,16.051556,0.000000
2.20,1,2,90,91.051556,107.198994,16.147438,1.051556
1.22,1,1,105,105.000000,119.330837,14.330837,0.000000

In [8]:
display(q_df)

                total_queue_length
day time
1   0.000000                     0
    15.000000                    0
    30.000000                    1
    30.878880                    0
    45.000000                    1
    46.506976                    0
    60.000000                    1
    62.145497                    0
    75.000000                    2
    75.005773                    1
    75.640157                    0
    90.000000                    1
    91.051556                    0
    105.000000                   1
    107.198994                   0

In [9]:
df1, q_df1 = clinic1.run_multiple_times(10)

-----------1-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:14: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:31: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:31: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:46: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:46: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:50: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:50: Pacjent 3.12 wchodzi do gabinetu 3
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:02: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:03: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:03: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:19: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:19: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:21: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:21: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:33: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:33: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:33: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:34: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:34: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:45: Pacjent 1.22 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:48: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:51: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:51: Pacjent 2.23 wchodzi do gabinetu 2
-----------2-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:11: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:12: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:15: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:29: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:42: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:59: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:00: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:16: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:19: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:19: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:30: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:36: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:36: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:44: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:48: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:48: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:48: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:48: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:57: Pacjent 2.23 wychodzi z gabinetu 2
-----------3-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:11: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:12: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:28: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:33: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:33: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:48: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:48: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:58: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:00: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:02: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:02: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:17: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:17: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:19: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:19: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:29: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:31: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:31: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:34: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:34: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:43: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:49: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:49: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:56: Pacjent 1.22 wychodzi z gabinetu 1
-----------4-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:16: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:20: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:20: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:30: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:34: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:34: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:47: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:48: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:48: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:49: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:49: Pacjent 3.12 wchodzi do gabinetu 3
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:02: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:02: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:08: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:08: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:16: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:16: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:17: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:17: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:24: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:24: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:27: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:30: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:41: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:41: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:43: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:44: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:52: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:52: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:59: Pacjent 2.23 wychodzi z gabinetu 2
-----------5-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:11: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:14: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:14: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:27: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:45: Pacjent 1.10 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:47: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:58: Pacjent 3.12 wychodzi z gabinetu 3
Czas 8:58: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:13: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:14: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:31: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:31: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:46: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:46: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:46: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:46: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:58: Pacjent 2.23 wychodzi z gabinetu 2
Czas 9:58: Pacjent 3.24 wychodzi z gabinetu 3
-----------6-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:16: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:16: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:27: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:32: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:32: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:33: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:44: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:47: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:47: Pacjent 3.12 wchodzi do gabinetu 3
Czas 9:00: Pacjent 1.13 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:03: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:03: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:04: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:17: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:17: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:20: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:20: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:34: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:34: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:35: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:35: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:46: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:46: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:48: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:51: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:51: Pacjent 3.24 wchodzi do gabinetu 3
-----------7-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:14: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:14: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:30: Pacjent 1.7 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:31: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:31: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:34: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:34: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:45: Pacjent 1.10 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:45: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:52: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:52: Pacjent 2.11 wchodzi do gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:08: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:13: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:16: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:16: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:29: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:31: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:33: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:41: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:58: Pacjent 1.22 wychodzi z gabinetu 1
-----------8-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki

In [10]:
display(df1)

,day,room,arrival_time,service_start_time,service_end_time,service_time,waiting_time
0,1,3,0,0.000000,13.805459,13.805459,0.000000
1,1,2,0,0.000000,14.417552,14.417552,0.000000
2,1,3,15,15.000000,27.466220,12.466220,0.000000
3,1,1,15,15.000000,31.375186,16.375186,0.000000
4,1,1,30,31.375186,45.407622,14.032436,1.375186
...,...,...,...,...,...,...,...
173,10,1,75,78.787434,93.660794,14.873360,3.787434
174,10,2,90,91.517454,104.506329,12.988875,1.517454
175,10,3,90,92.542162,104.656935,12.114773,2.542162
176,10,1,90,93.660794,108.916414,15.255620,3.660794
177,10,3,105,105.000000,117.749012,12.749012,0.000000

In [11]:
display(q_df1)

                total_queue_length
day time
1   0.000000                     0
    15.000000                    0
    30.000000                    1
    31.375186                    0
    45.000000                    3
...                            ...
10  91.517454                    2
    92.542162                    1
    93.660794                    0
    105.000000                   1
    108.916414                   0

[173 rows x 1 columns]

In [12]:
q_df1['total_queue_length'].value_counts()

total_queue_length
0    80
1    57
2    31
3     5
Name: count, dtype: int64

In [15]:
df1['service_start_time'].value_counts()

service_start_time
0.000000     26
15.000000    16
75.000000    14
30.000000    10
45.000000    10
             ..
61.559231     1
78.787434     1
91.517454     1
92.542162     1
93.660794     1
Name: count, Length: 90, dtype: int64