In [17]:
import matplotlib
matplotlib.use('TkAgg')  # or 'Qt5Agg'
import numpy as np
import simpy
import matplotlib.pyplot as plt
import random
import pandas as pd

In [18]:
class Patient:
    def __init__(self, id):
        self.id = id
        self.arrival_time = None
        self.service_start_time = None
        self.service_end_time = None
        self.room = None
        self.real_service_time = None

In [19]:
class Room:
    def __init__(self, id, env):
        self.id = id
        self.patients_served = 0
        self.no_show = 0
        self.queue = []
        self.queue_len_dict = dict()
        self.resource = simpy.Resource(env, capacity=1)
    def update_queue_len_dict(self, curr_time):
        self.queue_len_dict[curr_time] = len(self.queue)

In [20]:
class Clinic:
    def __init__(self, number_of_rooms, planned_service_time, no_show=0.2, seed=None, sim_time=480):
        self.env = simpy.Environment()

        self.curr_patient_id = 1
        
        self.planned_service_time = planned_service_time
        self.no_show = no_show
        self.sim_time = sim_time

        self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(number_of_rooms)]
        self.processed_patients = []
        

        self.seed = seed
        if self.seed:
            random.seed(self.seed)
            np.random.seed(self.seed)

    def readable_time(self):
        hours = 8 + int(self.env.now // 60)
        minutes = int(self.env.now % 60)
        if len(str(minutes)) == 1:
            return f"{hours}:0{minutes}"
        return f"{hours}:{minutes}"

    def generate_patients(self, room):

        def randomized_service_time(mean=15, std=2):
            return max(np.random.normal(mean, std), 1)

        def time_between_new_patients():
            return self.planned_service_time

        while True:
            if self.env.now > self.sim_time - self.planned_service_time:  # Pacjenci nie przychodzą przed {service_time} zamknięciem
                break

            patient = Patient(id=f"{room.id}.{self.curr_patient_id}")
            patient.room = room.id
            patient.real_service_time = randomized_service_time()

            if random.random() < self.no_show:  #pacjent nie przyszedl
                print(f'Czas {self.readable_time()}: Pacjent {patient.id} nie pojawił w gabinecie {room.id} w ciągu {self.planned_service_time} minut')
                room.no_show += 1

            else:  #pacjent przyszedl
                patient.arrival_time = self.env.now
                print(f"Czas {self.readable_time()}: Pacjent {patient.id} przybył do kliniki")
                self.env.process(self.serve_patient(patient, room))

            self.curr_patient_id += 1
            yield self.env.timeout(time_between_new_patients())

    def serve_patient(self, patient, room):
        room.queue.append(patient.id)
        room.update_queue_len_dict(curr_time=self.env.now)

        with room.resource.request() as request:
            yield request
            patient.service_start_time = self.env.now
            room.queue.remove(patient.id)
            room.update_queue_len_dict(curr_time=self.env.now)

            print(f"Czas {self.readable_time()}: Pacjent {patient.id} wchodzi do gabinetu {room.id} ")

            yield self.env.timeout(patient.real_service_time)

            patient.service_end_time = self.env.now
            room.patients_served += 1
            print(f"Czas {self.readable_time()}: Pacjent {patient.id} wychodzi z gabinetu {room.id}")
            self.processed_patients.append(patient)

    def reset(self):
        self.env = simpy.Environment()
        self.curr_patient_id = 1
        self.list_rooms = [Room(id=i + 1, env=self.env) for i in range(len(self.list_rooms))]
        self.processed_patients = []

    def run(self, day=1):
        def sum_queue_len_data():
            all_times = set()
            for room in self.list_rooms:
                all_times.update(room.queue_len_dict.keys())

            all_times = sorted(all_times)
            queue_data = []
            last_known = {room.id: 0 for room in self.list_rooms}  # cache

            for time in all_times:
                for room in self.list_rooms:
                    if time in room.queue_len_dict:
                        last_known[room.id] = room.queue_len_dict[time]

                total_queue = sum(last_known.values())
                queue_data.append({
                    'day': day,
                    'time': time,
                    'total_queue_length': total_queue
                })
            queue_data = pd.DataFrame(queue_data)
            queue_data = queue_data.set_index(["day", "time"])
            return queue_data
        
        for room in self.list_rooms:
            self.env.process(self.generate_patients(room))
        self.env.run(until=self.sim_time + 0.01)
        df = pd.DataFrame([
            {
                "day": day,
                "id": p.id,
                "room": p.room,
                "arrival_time": p.arrival_time,
                "service_start_time": p.service_start_time,
                "service_end_time": p.service_end_time,
                "service_time": p.service_end_time - p.service_start_time,
                "waiting_time": p.service_start_time - p.arrival_time
            }
            for p in self.processed_patients
        ])
        df = df.set_index("id")
        queue_df = sum_queue_len_data()
        return df, queue_df

    def run_multiple_times(self, n):

        # sum_no_show = 0
        # sum_patients_served = 0

        for i in range(1, n + 1):
            print(f"-----------{i}-----------")
            self.reset()
            single_df, single_queue_df = self.run(i)

            # for room in self.list_rooms:
            #     sum_no_show += room.no_show
            #     sum_patients_served += room.patients_served

            multiple_df = pd.concat([multiple_df, single_df], ignore_index=True) if i > 1 else single_df
            multiple_queue_df = pd.concat([multiple_queue_df, single_queue_df]) if i > 1 else single_queue_df
        # return multiple_df, sum_patients_served, sum_no_show
        return multiple_df, multiple_queue_df

In [21]:
clinic1 = Clinic(number_of_rooms=3, planned_service_time=15, sim_time=120)

In [22]:
df, q_df = clinic1.run()

Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:14: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:16: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:16: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:29: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:44: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:47: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:47: Pacjent 1.10 wchodzi do gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:02: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:02: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:04: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:04: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:21: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:21: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:26: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:26: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:38: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:44: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:57: Pacjent 1.22 wychodzi z gabinetu 1
Czas 9:59: Pacjent 3.24 wychodzi z gabinetu 3

In [23]:
display(df)

,day,room,arrival_time,service_start_time,service_end_time,service_time,waiting_time
id,,,,,,,
3.3,1,3,0,0.000000,14.683183,14.683183,0.000000
2.2,1,2,0,0.000000,16.042333,16.042333,0.000000
1.4,1,1,15,15.000000,29.685928,14.685928,0.000000
3.6,1,3,15,15.000000,30.152118,15.152118,0.000000
2.5,1,2,15,16.042333,30.762490,14.720157,1.042333
2.8,1,2,30,30.762490,44.736758,13.974269,0.762490
3.9,1,3,30,30.152118,45.495230,15.343112,0.152118
1.7,1,1,30,30.000000,47.757457,17.757457,0.000000
2.11,1,2,45,45.000000,62.089499,17.089499,0.000000
1.10,1,1,45,47.757457,64.595621,16.838165,2.757457
2.14,1,2,60,62.089499,81.189775,19.100276,2.089499
1.13,1,1,60,64.595621,86.487299,21.891677,4.595621
2.17,1,2,75,81.189775,98.046881,16.857106,6.189775
1.16,1,1,75,86.487299,104.651078,18.163780,11.487299
1.22,1,1,105,105.000000,117.719611,12.719611,0.000000
3.24,1,3,105,105.000000,119.622503,14.622503,0.000000

In [24]:
display(q_df)

                total_queue_length
day time
1   0.000000                     0
    15.000000                    1
    16.042333                    0
    30.000000                    2
    30.152118                    1
    30.762490                    0
    45.000000                    1
    47.757457                    0
    60.000000                    2
    62.089499                    1
    64.595621                    0
    75.000000                    2
    81.189775                    1
    86.487299                    0
    105.000000                   0

In [25]:
df1, q_df1 = clinic1.run_multiple_times(10)

-----------1-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:14: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:28: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:28: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:42: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 1.10 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:46: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:57: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:11: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:16: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:16: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:20: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:20: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:36: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:36: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:50: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:50: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:52: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:52: Pacjent 3.24 wchodzi do gabinetu 3
-----------2-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:11: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:13: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:16: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:16: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:29: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:33: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:42: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:49: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:49: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:56: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:02: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:02: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:07: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:07: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:17: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:17: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:24: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:24: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:32: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:32: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:32: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:32: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:42: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:42: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:44: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:49: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:49: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:57: Pacjent 3.21 wychodzi z gabinetu 3
-----------3-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:00: Pacjent 3.3 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:28: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:42: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:43: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:45: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:58: Pacjent 3.12 wychodzi z gabinetu 3
Czas 8:59: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:00: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:15: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:16: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:16: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:18: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:27: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:30: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:37: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:37: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:45: Pacjent 1.22 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:45: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:45: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:58: Pacjent 1.19 wychodzi z gabinetu 1
-----------4-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:13: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:19: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:19: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:29: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:31: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:31: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:34: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:34: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:43: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:49: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:49: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:58: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:04: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:04: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:06: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:06: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:14: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:15: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:15: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:19: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:19: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:31: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:31: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:34: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:34: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:48: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:48: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:48: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:48: Pacjent 1.22 wchodzi do gabinetu 1
-----------5-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:16: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:16: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:29: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:30: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:44: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:59: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:02: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:02: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:02: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:13: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:15: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:28: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:30: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:44: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:45: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:49: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:49: Pacjent 2.23 wchodzi do gabinetu 2
-----------6-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:16: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:16: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:31: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:31: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:42: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:44: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:59: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:02: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:02: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:03: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:03: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:13: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:17: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:17: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:18: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:18: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:29: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:32: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:32: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:35: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:44: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:57: Pacjent 3.24 wychodzi z gabinetu 3
Czas 9:59: Pacjent 2.23 wychodzi z gabinetu 2
-----------7-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:12: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:13: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:31: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:31: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:44: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:45: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:46: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:46: Pacjent 2.11 wchodzi do gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:01: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:01: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:01: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:01: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:02: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:12: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:20: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:20: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:29: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:32: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:32: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:33: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:33: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:46: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:46: Pacjent 1.22 wchodzi do gabinetu 1

In [26]:
display(df1)

,day,room,arrival_time,service_start_time,service_end_time,service_time,waiting_time
0,1,3,0,0.00000,13.320898,13.320898,0.00000
1,1,1,0,0.00000,14.060053,14.060053,0.00000
2,1,2,15,15.00000,27.741019,12.741019,0.00000
3,1,1,15,15.00000,28.866721,13.866721,0.00000
4,1,3,15,15.00000,28.885622,13.885622,0.00000
...,...,...,...,...,...,...,...
172,10,1,60,65.21209,80.581936,15.369846,5.21209
173,10,2,75,75.00000,88.098904,13.098904,0.00000
174,10,2,90,90.00000,103.825736,13.825736,0.00000
175,10,1,90,90.00000,106.126623,16.126623,0.00000
176,10,3,90,90.00000,106.737866,16.737866,0.00000

In [27]:
display(q_df1)

                total_queue_length
day time
1   0.000000                     0
    15.000000                    0
    30.000000                    0
    45.000000                    0
    60.000000                    0
...                            ...
10  65.212090                    0
    75.000000                    0
    90.000000                    0
    105.000000                   1
    106.737866                   0

[157 rows x 1 columns]

In [28]:
q_df1['total_queue_length'].value_counts()

total_queue_length
0    78
1    52
2    24
3     3
Name: count, dtype: int64

In [29]:
df1['service_start_time'].value_counts()

service_start_time
0.000000     24
45.000000    20
15.000000    17
90.000000    12
75.000000    11
             ..
33.526672     1
45.465505     1
49.388611     1
60.341361     1
65.212090     1
Name: count, Length: 75, dtype: int64

In [31]:
df, queue_df = clinic1.run_multiple_times(n=1000) 

df.to_csv("../wyniki/wyniki_z_um.csv")
queue_df.to_csv("../wyniki/kolejki_z_um.csv")

-----------1-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:14: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:16: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:16: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:28: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:28: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:43: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:44: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:49: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:49: Pacjent 3.12 wchodzi do gabinetu 3
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:01: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:14: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:15: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:17: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:17: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:29: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:32: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:45: Pacjent 1.22 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:45: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:50: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:57: Pacjent 3.24 wychodzi z gabinetu 3
-----------2-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:12: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:17: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:17: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:31: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:31: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:32: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:32: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:44: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:47: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:47: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:48: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:48: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:57: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:04: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:04: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:04: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:04: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:14: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:18: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:18: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:19: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:19: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:27: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:36: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:36: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:42: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:50: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:50: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:59: Pacjent 1.22 wychodzi z gabinetu 1
Czas 9:59: Pacjent 2.23 wychodzi z gabinetu 2
-----------3-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:10: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:11: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:34: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:34: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:44: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:49: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:49: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:59: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:03: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:03: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:12: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:16: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:16: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:21: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:21: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:29: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 1.19 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:34: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:34: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:35: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:47: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:47: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:47: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:47: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:59: Pacjent 1.22 wychodzi z gabinetu 1
Czas 9:59: Pacjent 3.24 wychodzi z gabinetu 3
-----------4-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:11: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:17: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:17: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:17: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:31: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:31: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:36: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:36: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:41: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:45: Pacjent 1.10 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:47: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:47: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:52: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:58: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:01: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:01: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:11: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:15: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:18: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:18: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:27: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:31: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:31: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:36: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:36: Pacjent 3.21 wchodzi do gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:48: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:48: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:53: Pacjent 3.21 wychodzi z gabinetu 3
Czas 9:53: Pacjent 3.24 wchodzi do gabinetu 3
-----------5-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:15: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:17: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:17: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:27: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:27: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:36: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:36: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:46: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:46: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:51: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:51: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:57: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:04: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:04: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:04: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:04: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:13: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:18: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:18: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:21: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:21: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:32: Pacjent 1.16 wychodzi z gabinetu 1
Czas 9:32: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:33: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:33: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:34: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:49: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:49: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:50: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:50: Pacjent 1.22 wchodzi do gabinetu 1
-----------6-----------
Czas 8:00: Pacjent 1.1 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:12: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 przybył do kliniki
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 3.6 wchodzi do gabinetu 3
Czas 8:17: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:17: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:28: Pacjent 3.6 wychodzi z gabinetu 3
Czas 8:29: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:33: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:33: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:42: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:44: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:45: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:48: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:48: Pacjent 2.11 wchodzi do gabinetu 2
Czas 8:59: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 nie pojawił w gabinecie 2 w ciągu 15 minut
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:00: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:00: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:03: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:13: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:15: Pacjent 1.16 nie pojawił w gabinecie 1 w ciągu 15 minut
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:15: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:17: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:17: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 9:30: Pacjent 1.19 wchodzi do gabinetu 1
Czas 9:30: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:30: Pacjent 2.20 wchodzi do gabinetu 2
Czas 9:30: Pacjent 3.18 wychodzi z gabinetu 3
Czas 9:43: Pacjent 1.19 wychodzi z gabinetu 1
Czas 9:44: Pacjent 2.20 wychodzi z gabinetu 2
Czas 9:45: Pacjent 1.22 przybył do kliniki
Czas 9:45: Pacjent 2.23 przybył do kliniki
Czas 9:45: Pacjent 3.24 przybył do kliniki
Czas 9:45: Pacjent 1.22 wchodzi do gabinetu 1
Czas 9:45: Pacjent 2.23 wchodzi do gabinetu 2
Czas 9:45: Pacjent 3.24 wchodzi do gabinetu 3
Czas 9:58: Pacjent 3.24 wychodzi z gabinetu 3
Czas 9:59: Pacjent 2.23 wychodzi z gabinetu 2
-----------7-----------
Czas 8:00: Pacjent 1.1 przybył do kliniki
Czas 8:00: Pacjent 2.2 przybył do kliniki
Czas 8:00: Pacjent 3.3 przybył do kliniki
Czas 8:00: Pacjent 1.1 wchodzi do gabinetu 1
Czas 8:00: Pacjent 2.2 wchodzi do gabinetu 2
Czas 8:00: Pacjent 3.3 wchodzi do gabinetu 3
Czas 8:13: Pacjent 2.2 wychodzi z gabinetu 2
Czas 8:14: Pacjent 3.3 wychodzi z gabinetu 3
Czas 8:14: Pacjent 1.1 wychodzi z gabinetu 1
Czas 8:15: Pacjent 1.4 przybył do kliniki
Czas 8:15: Pacjent 2.5 przybył do kliniki
Czas 8:15: Pacjent 3.6 nie pojawił w gabinecie 3 w ciągu 15 minut
Czas 8:15: Pacjent 1.4 wchodzi do gabinetu 1
Czas 8:15: Pacjent 2.5 wchodzi do gabinetu 2
Czas 8:28: Pacjent 1.4 wychodzi z gabinetu 1
Czas 8:30: Pacjent 1.7 przybył do kliniki
Czas 8:30: Pacjent 2.8 przybył do kliniki
Czas 8:30: Pacjent 3.9 przybył do kliniki
Czas 8:30: Pacjent 1.7 wchodzi do gabinetu 1
Czas 8:30: Pacjent 3.9 wchodzi do gabinetu 3
Czas 8:30: Pacjent 2.5 wychodzi z gabinetu 2
Czas 8:30: Pacjent 2.8 wchodzi do gabinetu 2
Czas 8:44: Pacjent 3.9 wychodzi z gabinetu 3
Czas 8:45: Pacjent 1.10 przybył do kliniki
Czas 8:45: Pacjent 2.11 przybył do kliniki
Czas 8:45: Pacjent 3.12 przybył do kliniki
Czas 8:45: Pacjent 3.12 wchodzi do gabinetu 3
Czas 8:47: Pacjent 1.7 wychodzi z gabinetu 1
Czas 8:47: Pacjent 1.10 wchodzi do gabinetu 1
Czas 8:47: Pacjent 2.8 wychodzi z gabinetu 2
Czas 8:47: Pacjent 2.11 wchodzi do gabinetu 2
Czas 9:00: Pacjent 1.13 przybył do kliniki
Czas 9:00: Pacjent 2.14 przybył do kliniki
Czas 9:00: Pacjent 3.15 przybył do kliniki
Czas 9:01: Pacjent 2.11 wychodzi z gabinetu 2
Czas 9:01: Pacjent 2.14 wchodzi do gabinetu 2
Czas 9:02: Pacjent 3.12 wychodzi z gabinetu 3
Czas 9:02: Pacjent 3.15 wchodzi do gabinetu 3
Czas 9:05: Pacjent 1.10 wychodzi z gabinetu 1
Czas 9:05: Pacjent 1.13 wchodzi do gabinetu 1
Czas 9:15: Pacjent 1.16 przybył do kliniki
Czas 9:15: Pacjent 2.17 przybył do kliniki
Czas 9:15: Pacjent 3.18 przybył do kliniki
Czas 9:16: Pacjent 2.14 wychodzi z gabinetu 2
Czas 9:16: Pacjent 2.17 wchodzi do gabinetu 2
Czas 9:18: Pacjent 3.15 wychodzi z gabinetu 3
Czas 9:18: Pacjent 3.18 wchodzi do gabinetu 3
Czas 9:20: Pacjent 1.13 wychodzi z gabinetu 1
Czas 9:20: Pacjent 1.16 wchodzi do gabinetu 1
Czas 9:30: Pacjent 1.19 przybył do kliniki
Czas 9:30: Pacjent 2.20 przybył do kliniki
Czas 9:30: Pacjent 3.21 przybył do kliniki
Czas 9:32: Pacjent 2.17 wychodzi z gabinetu 2
Czas 9:32: Pacjent 2.20 wchodzi do gabinetu 2